/**
 * ZK-Identity – Third-Party Verifier
 *
 * This snippet shows how a verifier (e.g. a KYC service, DApp backend)
 * should validate a SnarkJS proof so that the prover cannot tamper with
 * the public signals (threshold, walletAddress, etc.).
 *
 * Dependencies: snarkjs, circomlibjs
 * npm install snarkjs circomlibjs
 *
 * Assumed files (generated by your Circom build pipeline):
 *   - selective_disclosure_final.zkey   (proving key)
 *   - verification_key.json             (verification key exported from zkey)
 */

import * as snarkjs from "snarkjs";
import { buildPoseidon } from "circomlibjs";
import * as fs from "fs";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Public signal layout for SelectiveDisclosure circuit.
 *
 * SnarkJS returns publicSignals as a flat string array in the ORDER that
 * the circuit declares its public inputs (output signals first, then inputs).
 *
 * For our circuit (no output signals, 4 public inputs declared left-to-right):
 *   index 0 → credentialRoot
 *   index 1 → walletAddress
 *   index 2 → threshold
 *   index 3 → expectedValueHash
 */
const PUBLIC_SIGNAL_INDEX = {
  key: 0,
  credentialRoot: 1,
  publicCommitment: 2,
  threshold: 3,
  expectedValueHash: 4,
} as const;

export interface ProofBundle {
  proof: any;          // Groth16 proof from snarkjs.groth16.fullProve
  publicSignals: string[]; // Flat string array from the same call
}

export interface VerificationRequest {
  proofBundle: ProofBundle;
  /** The key the verifier expects to see */
  expectedKey: bigint;
  /** The on-chain Merkle root the verifier trusts (read from contract) */
  expectedCredentialRoot: bigint;
  /** The identity commitment the verifier is authenticating */
  expectedPublicCommitment: bigint;
  /**
   * For numeric/date claims: the minimum value the verifier requires.
   * Set to 0n if this is a string-equality proof.
   */
  requiredThreshold?: bigint;
  /**
   * For string/email claims: the hash the verifier expects.
   * Set to 0n if this is a numeric-range proof.
   */
  requiredValueHash?: bigint;
}

// ─────────────────────────────────────────────────────────────────────────────
// Core verification function
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Verifies a ZK selective-disclosure proof.
 *
 * IMPORTANT: After cryptographic verification, we MUST re-check all public
 * signals against our own trusted values. A valid proof only shows the
 * prover knows a witness consistent with the declared public signals –
 * it does NOT prove the public signals themselves are correct unless the
 * verifier independently checks them.
 */
export async function verifySelectiveDisclosure(
  verificationKeyPath: string,
  req: VerificationRequest
): Promise<{ valid: boolean; reason?: string }> {
  // 1. Load verification key
  const vKey = JSON.parse(fs.readFileSync(verificationKeyPath, "utf8"));

  const { proof, publicSignals } = req.proofBundle;

  // 2. Cryptographic proof verification (Groth16)
  const cryptoValid = await snarkjs.groth16.verify(vKey, publicSignals, proof as any);
  if (!cryptoValid) {
    return { valid: false, reason: "Groth16 proof is invalid" };
  }

  // 3. Re-check public signals against verifier-controlled trusted values
  //    This prevents a prover from submitting a valid proof with DIFFERENT
  //    public signals (e.g. a lower threshold or a different wallet).

  const proofKey = BigInt(publicSignals[PUBLIC_SIGNAL_INDEX.key]);
  if (proofKey !== req.expectedKey) {
    return {
      valid: false,
      reason: `key mismatch: got ${proofKey}, expected ${req.expectedKey}`,
    };
  }

  const proofRoot = BigInt(publicSignals[PUBLIC_SIGNAL_INDEX.credentialRoot]);
  if (proofRoot !== req.expectedCredentialRoot) {
    return {
      valid: false,
      reason: `credentialRoot mismatch: got ${proofRoot}, expected ${req.expectedCredentialRoot}`,
    };
  }

  const proofCommitment = BigInt(publicSignals[PUBLIC_SIGNAL_INDEX.publicCommitment]);
  if (proofCommitment !== req.expectedPublicCommitment) {
    return {
      valid: false,
      reason: `publicCommitment mismatch: got ${proofCommitment}, expected ${req.expectedPublicCommitment}`,
    };
  }

  // 4. Validate threshold if this is a numeric/date claim
  if (req.requiredThreshold !== undefined && req.requiredThreshold > 0n) {
    const proofThreshold = BigInt(publicSignals[PUBLIC_SIGNAL_INDEX.threshold]);
    if (proofThreshold < req.requiredThreshold) {
      return {
        valid: false,
        reason: `threshold too low: proof used ${proofThreshold}, verifier requires >= ${req.requiredThreshold}`,
      };
    }
  }

  // 5. Validate expected value hash if this is a string-equality claim
  if (req.requiredValueHash !== undefined && req.requiredValueHash > 0n) {
    const proofHash = BigInt(
      publicSignals[PUBLIC_SIGNAL_INDEX.expectedValueHash]
    );
    if (proofHash !== req.requiredValueHash) {
      return {
        valid: false,
        reason: `expectedValueHash mismatch: got ${proofHash}, expected ${req.requiredValueHash}`,
      };
    }
  }

  return { valid: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// Convenience: generate a proof then verify in one call (for testing)
// ─────────────────────────────────────────────────────────────────────────────

export async function proveAndVerify(params: {
  inputJsonPath: string;
  wasmPath: string;
  zkeyPath: string;
  verificationKeyPath: string;
  expectedKey: bigint;
  expectedCredentialRoot: bigint;
  expectedPublicCommitment: bigint;
  requiredThreshold?: bigint;
  requiredValueHash?: bigint;
}): Promise<void> {
  console.log("━━━ Generating proof ━━━");
  const input = JSON.parse(fs.readFileSync(params.inputJsonPath, "utf8"));

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    params.wasmPath,
    params.zkeyPath
  );

  console.log("Proof generated successfully.");
  console.log("Public signals:", publicSignals);

  // Optional: write proof to disk for the prover to submit
  fs.writeFileSync("proof.json", JSON.stringify(proof, null, 2));
  fs.writeFileSync("public.json", JSON.stringify(publicSignals, null, 2));

  console.log("\n━━━ Verifying proof ━━━");
  const result = await verifySelectiveDisclosure(params.verificationKeyPath, {
    proofBundle: { proof, publicSignals },
    expectedKey: params.expectedKey,
    expectedCredentialRoot: params.expectedCredentialRoot,
    expectedPublicCommitment: params.expectedPublicCommitment,
    requiredThreshold: params.requiredThreshold,
    requiredValueHash: params.requiredValueHash,
  });

  if (result.valid) {
    console.log("✅ Proof is VALID – all claims verified successfully");
  } else {
    console.error(`❌ Proof is INVALID: ${result.reason}`);
    process.exit(1);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// On-chain analogue – what the Solidity verifier should check
// ─────────────────────────────────────────────────────────────────────────────
/*
  // Solidity pseudo-code (assumes auto-generated IVerifier from snarkjs):

  function verifyAgeProof(
      uint[2] calldata _pA,
      uint[2][2] calldata _pB,
      uint[2] calldata _pC,
      uint[4] calldata _pubSignals  // [credentialRoot, walletAddress, threshold, expectedValueHash]
  ) external view {
      // 1. Cryptographic check
      require(IVerifier(verifierAddr).verifyProof(_pA, _pB, _pC, _pubSignals), "Bad proof");

      // 2. Trust the on-chain root, not what the prover claims
      require(_pubSignals[0] == credentialRoot, "Wrong root");

      // 3. Verify sender owns the identity
      require(_pubSignals[1] == uint256(uint160(msg.sender)), "Wrong wallet");

      // 4. Enforce our business rule threshold, not the prover's
      require(_pubSignals[2] >= MIN_AGE_THRESHOLD, "Threshold too low");
  }
*/

// ─────────────────────────────────────────────────────────────────────────────
// Standalone verification from pre-existing proof files
// (used when proof was generated client-side and sent to verifier)
// ─────────────────────────────────────────────────────────────────────────────

export async function verifyFromFiles(params: {
  proofPath: string;          // proof.json from snarkjs
  publicSignalsPath: string;  // public.json from snarkjs
  verificationKeyPath: string;
  expectedKey: bigint;
  expectedCredentialRoot: bigint;
  expectedPublicCommitment: bigint;
  requiredThreshold?: bigint;
  requiredValueHash?: bigint;
}): Promise<void> {
  const proof = JSON.parse(fs.readFileSync(params.proofPath, "utf8"));
  const publicSignals: string[] = JSON.parse(
    fs.readFileSync(params.publicSignalsPath, "utf8")
  );

  const result = await verifySelectiveDisclosure(params.verificationKeyPath, {
    proofBundle: { proof, publicSignals },
    expectedKey: params.expectedKey,
    expectedCredentialRoot: params.expectedCredentialRoot,
    expectedPublicCommitment: params.expectedPublicCommitment,
    requiredThreshold: params.requiredThreshold,
    requiredValueHash: params.requiredValueHash,
  });

  if (result.valid) {
    console.log("✅ Proof VALID");
  } else {
    console.error(`❌ Proof INVALID: ${result.reason}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Example invocation (comment out for library use)
// ─────────────────────────────────────────────────────────────────────────────

// verifyFromFiles({
//   proofPath: "proof.json",
//   publicSignalsPath: "public.json",
//   verificationKeyPath: "verification_key.json",
//   expectedCredentialRoot: BigInt("0x..."),   // read from your smart contract
//   expectedWalletAddress: BigInt("0x..."),    // the address you are authenticating
//   requiredThreshold: 18000000n,              // for age: YYYYMMDD of (today - 18 years)
// });
